### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
This works on Windows, which has been very very difficult. The *eureka* moment came after reading this issue: https://github.com/gotwarlost/istanbul/issues/64

### CODE REVIEW

**Comment by dotnetCarpenter** [comment]
Ok. it worked. @dionyziz need to give me access to this repo or create a codecov account, add stream.js and get a token, which you need to setup in the travis environment as CODECOV_TOKEN.

**Comment by dotnetCarpenter** [comment]
Or I might be wrong.
>Repo tokens are not required for public repos tested on Travis, CircleCI or AppVeyor.
https://github.com/cainus/codecov.io/

**Comment by dionyziz** [comment]
I created a codecov account and it seems that stream.js is already in, so we're all set. Can you sync this up with master so that we can see a good diff before merging? Thanks!

**Comment by dotnetCarpenter** [comment]
hmm. it should be in sync since it is based off the travis branch (PR #21).

**Comment by dotnetCarpenter** [comment]
one withstanding issue with this PR is that codecov breaks `npm test` locally, due to missing configuration. Is it just here or do you see the same?

**Comment by dotnetCarpenter** [comment]
@dionyziz You can see exactly which paths we haven't tested if you run `npm test` and open `stream.js/coverage/lcov-report/lib/index.js.html` in your browser.

**Comment by dotnetCarpenter** [comment]
@dionyziz or at the codecov website: https://codecov.io/github/dionyziz/stream.js?branch=master (click on the index.js file link)

**Comment by dionyziz** [comment]
Nice – looking good.

**Pull request merged**
